---
version: "3.7"
services:
  kasm:
    build:
      dockerfile: Dockerfile
    image: ghcr.io/odu-cga-cubesat/sealion-workspace-image:v1.1.0
    ports:
      - "6901:6901"
      - "50000:50000"
    environment:
      VNC_PW: password
    shm_size: '512m'
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    network_mode: bridge
    volumes:
      - type: bind
        source: ./kasm_user
        target: /home/kasm-user
      - /run/udev:/run/udev:ro
      - /dev:/dev
#      - type: bind
#        source: /run/user/1000/pulse/
#        target: /run/user/1000/pulse/
    device_cgroup_rules:
      - "c 188:* rmw"
    privileged: true
    security_opt:
      - seccomp=unconfined
...
